# Generated by Django 5.0.7 on 2026-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_issuelink_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
