# Generated by Django 5.0.7 on 2026-07-06 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('mobile', 'mobile'), ('infra', 'infra'), ('job', 'job'), ('test', 'test'), ('other', 'other')], default='other', max_length=20)),
                ('kind', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('active', 'active'), ('planned', 'planned'), ('removed', 'removed')], default='active', max_length=20)),
                ('origin', models.CharField(default='mcp', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_items', to='events.project')),
            ],
        ),
    ]
